# Generated by Django 5.0.2 on 2024-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
