# Generated by Django 5.0.2 on 2024-02-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_alter_transacao_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacionamento',
            name='transacoes',
            field=models.ManyToManyField(blank=True, related_name='transacoes', to='gerencia.transacao'),
        ),
    ]
